services:
    app:
        build: .
        command: fastapi run main.py --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        environment:
            - DATABASE_URL=postgresql://shop_db:shop_db@db:5432/shop_db
        depends_on:
            - db
    db:
        build: ./db
        container_name: postgres_db
        environment:
            POSTGRES_USER: shop_db
            POSTGRES_PASSWORD: shop_db
            POSTGRES_DB: shop_db
        