version: '3.8'

services:
    app:
        build: .
        command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; fastapi run main.py --host 0.0.0.0 --port 8000'
        volumes:
            - .:/shop
        ports:
            - 8000:8000
        environment:
            - DATABASE_URL=postgresql://shop_db:shop_db@db:5432/shop_db
        depends_on:
            - db
    db:
        container_name: postgres_db
        image: postgres:16.4-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - 5432
        environment:
            - POSTGRESS_DB=shop_db
            - POSTGRESS_DB_USER=shop_db
            - POSTGRESS_DB_PASSWORD=shop_db

volumes:
    postgres_data: