create table if not exists product (
    id integer primary key GENERATED by DEFAULT as identity,
    name text,
    description text,
    price int, 
    count int
);

create table if not exists orders (
    id integer primary key GENERATED by DEFAULT as identity,
    date date,
    status text
);

create table if not exists order_item (
    id integer primary key GENERATED by DEFAULT as identity,
    order_id integer references orders(id),
    product_id integer references product(id),
    count integer
);